version: '3.8'

services:
  db:
    image: postgres:14.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env

  app:
    build: .
    restart: on-failure
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres:
